# Generated by Django 6.0.4 on 2026-06-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('team_leader', 'Team Leader'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
